version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.4
workflows:
  build_test_deploy:
    jobs:
      - build_test
      - aws-ecr/build_and_push_image:
          region: us-east-1
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: "$MYFLASKREPO"
          tag: ${CIRCLE_BUILD_NUM}
          requires:
            - build_test
      - docker_hub_build_push_image

jobs:
  build_test:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            virtualenv helloworld
            . helloworld/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate
            python ./test.py syncdb
  docker_hub_build_push_image:
          docker:
            - image: circleci/python:2.7.14
          steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: false
            - run:
                name: Build and push Docker image to Docker Hub
                command: |
                  echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> ${BASH_ENV}
                  echo 'export IMAGE_NAME="$MYFLASKREPO"' >> ${BASH_ENV}
                  source ${BASH_ENV}
                  docker build -t ${DOCKER_USER}/${IMAGE_NAME} -t ${DOCKER_USER}/${IMAGE_NAME}:${TAG} .
                  echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
                  docker push ${DOCKER_USER}/${IMAGE_NAME}



            
            
